### ISSUE TITLE
リポジトリ名をlowercase(+hyphens)にしたい。したくない？

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/seichi-ranking-bff#76]

**Comment by inductor** [comment]
したい

**Comment by kory33** [comment]
してええか？（これ参照してるものって何かありましたっけ）

**Comment by kory33** [comment]
org全体で検索したら https://github.com/GiganticMinecraft/SeichiRankingBFF-API も出てきたけどここと API だけでまだクラスタに入ってない　変えるなら今のうちじゃ
